name: Build & Publish Notebooks to Pages

on:
  push:
    branches: [ main ]          # change to master if your default is master
    paths:
      - '**/*.ipynb'
      - '.github/workflows/publish-notebooks.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    # prevent running on forks
    if: ${{ github.repository == 'nd-cse-30124-fa25/cse-30124-homeworks' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install nbconvert
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert jupyterlab_pygments pygments

      # Convert every .ipynb -> HTML, mirroring folder structure under site/
      - name: Convert notebooks to HTML
        run: |
          mkdir -p site
          while IFS= read -r -d '' f; do
            outdir="site/$(dirname "$f" | sed 's|^\./||')"
            mkdir -p "$outdir"
            jupyter nbconvert --to html "$f" \
              --output "$(basename "${f%.ipynb}").html" \
              --output-dir "$outdir"
          done < <(find . -type f -name '*.ipynb' -not -path '*/.ipynb_checkpoints/*' -print0)

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    if: ${{ github.repository == 'nd-cse-30124-fa25/cse-30124-homeworks' }}
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4